### PR TITLE
Fix F401 infinite loop when adding duplicate symbols to __all__

### LINKED ISSUE #22221: F401 fix causes infinite loop adding duplicates to `__all__`
### Summary

How to reproduce:

```sh
$ mkdir foo
$ echo '
import foo.bar.module
import foo.baz.module

__all__ = []
' > foo/__init__.py

$ cargo run --bin ruff -- check test_f401_dup/foo/__init__.py --select F401 --preview --fix foo/__init__.py
```

`foo/__init__.py` looks like this after the fix is applied:

```python
import foo.bar.module
import foo.baz.module

__all__ = [
    "foo",
    ...,
    "foo",
    "foo",
    "foo",
    "foo",
]
```

It appears that `foo.baz.module` is never marked as used, and ruff keeps adding `foo` in `__all__`.

### Version

da188d5cf654d7ac5a1ff3606d2baef78fa63d70

### Context

Ran into this bug when I upgraded ruff to 0.14.10 in mlflow/mlflow

### PR DESCRIPTION
**Pull request by jonathan-fulton**
## Summary

Fixes #22221

Running `ruff check --fix` could enter an infinite loop when fixing F401 (unused imports) in `__init__.py` files that combine star imports with explicit imports of the same symbol.

## Problem

When adding symbols to `__all__` in `fix_by_reexporting`, duplicate symbols could be collected (e.g., when a module has both `from foo import *` and `from foo import bar`). Without deduplication, ruff would repeatedly add the same symbol to `__all__`, creating an infinite fix loop.

## Changes

Added a `dedup()` call after `sort_unstable()` in `fix_by_reexporting` to remove duplicate symbols before adding them to `__all__`.

## Test Plan

Tested with:
```python
# __init__.py
from .foo import *
from .foo import bar

__all__ = []
```

Before this fix, `ruff check --fix --unsafe-fixes` would loop infinitely. After this fix, it correctly adds each symbol once.

### CODE REVIEW

**Comment by dylwil3** [comment]
Thanks for your interest in contributing to Ruff! Unfortunately this does not seem to fix the linked issue:

```console
❯ gh pr checkout 23052

❯ mkdir foo && echo 'import foo.bar.module
import foo.baz.module

__all__ = ["foo"]' > foo/__init__.py

❯ cargo run -p ruff -- check --no-cache --isolated --select F401 --preview foo/__init__.py
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.15s
     Running `target/debug/ruff check --no-cache --isolated --select F401 --preview foo/__init__.py`
F401 [*] `foo.baz.module` imported but unused; consider removing, adding to `__all__`, or using a redundant alias
 --> foo/__init__.py:2:8
  |
1 | import foo.bar.module
2 | import foo.baz.module
  |        ^^^^^^^^^^^^^^
3 |
4 | __all__ = ["foo"]
  |
help: Add `foo` to __all__
1 | import foo.bar.module
2 | import foo.baz.module
3 |
  - __all__ = ["foo"]
4 + __all__ = ["foo", "foo"]

Found 1 error.
[*] 1 fixable with the `--fix` option.
```

Moreover, even if it did, we need to do more than just change the autofix - the help text is also incorrect in this situation. So I think we need something closer to what I started working on in this draft https://github.com/astral-sh/ruff/pull/23038

Finally, I'm not sure I understand the test case you tried. The autofix would add `bar` not `foo`, and there are no duplicates or infinite loops created (before or after this PR).
