### ISSUE TITLE
Ruff extension error while trying to find the Ruff binary in VS Code.

### ISSUE THREAD

**Issue by krave1986** [astral-sh/ruff#16086]
### Description

After upgrading Python to 3.13.2 from 3.12.4, this error occurs every time me opening VS Code.
Do you have any suggestions to avoid this?

Here is the log of the extension:

> 2025-02-10 09:20:47.589 [info] Name: Ruff
> 2025-02-10 09:20:47.589 [info] Module: ruff
> 2025-02-10 09:20:47.589 [info] Python extension loading
> 2025-02-10 09:20:47.589 [info] Waiting for interpreter from python extension.
> 2025-02-10 09:20:47.596 [info] Python extension loaded
> 2025-02-10 09:20:47.605 [info] Using interpreter: d:\learn\Python\learn-python-in-vscode\Libs\Psycopg 3\Official\Getting started with Psycopg 3\.venv\Scripts\python.exe
> 2025-02-10 09:20:48.635 [error] Error while trying to find the Ruff binary: Error: Traceback (most recent call last):
>   File "c:\Users\Administrator\.vscode\extensions\charliermarsh.ruff-2025.6.0-win32-x64\bundled\tool\find_ruff_binary_path.py", line 3, in <module>
>     import sysconfig
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\sysconfig\__init__.py", line 5, in <module>
>     import threading
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\threading.py", line 35, in <module>
>     _start_joinable_thread = _thread.start_joinable_thread
>                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: module '_thread' has no attribute 'start_joinable_thread'
> 
> 2025-02-10 09:20:49.377 [info] Falling back to bundled executable: c:\Users\Administrator\.vscode\extensions\charliermarsh.ruff-2025.6.0-win32-x64\bundled\libs\bin\ruff.exe

**Comment by dhruvmanila** [comment]
Can you specify how did you upgrade Python? Can you try re-creating the virtual environment?

**Comment by krave1986** [comment]
Hi @dhruvmanila ,

I upgraded Python using the official installer. My OS is Windows 10.

Now I can fully reproduce the issue and I think the problem might be related to the environment variable `PYTHONHOME`.

I have Python 3.12.6 and 3.13.2 globally installed on my machine.
Then I set up this structure on my file system.

> ├──py_3_12_6
> │  └──test.py
> ├──py_3_13_2
> │  └──test.py

My steps:

1. set `PYTHONHOME` as `C:\Users\Administrator\AppData\Local\Programs\Python\Python312`
2. open folder py_3_12_6 in VS Code and run command: `Python: Create Environment...`
3. choose `Venv` and select `Python 3.12.6`
4. set `PYTHONHOME` as `C:\Users\Administrator\AppData\Local\Programs\Python\Python313`
5. open folder py_3_13_2 in VS Code and run command: `Python: Create Environment...`
6. choose `Venv` and select `Python 3.13.2`

After these steps, if you go back to the py_3_12_6 folder and open the test.py file, you will also see the error.
