### ISSUE TITLE
Fails to build with salsa 0.28.4

### ISSUE THREAD

**Issue by musicinmybrain** [astral-sh/ruff#28726]
### Summary

```
$ git clone https://github.com/astral-sh/ruff.git
$ cd ruff
$ cargo build
[success]
$ cargo update salsa
    Updating crates.io index
     Locking 3 packages to latest compatible versions
    Updating salsa v0.28.2 -> v0.28.4
    Updating salsa-macro-rules v0.28.2 -> v0.28.4
    Updating salsa-macros v0.28.2 -> v0.28.4
note: pass `--verbose` to see 199 unchanged dependencies behind latest
[…]
error[E0407]: method `hash` is not a member of trait `salsa::HashEqLike`
   --> crates/ruff_python_ast/src/name.rs:176:5
    |
176 | /     fn hash<H: Hasher>(&self, state: &mut H) {
177 | |         self.as_str().hash(state);
178 | |     }
    | |_____^ not a member of trait `salsa::HashEqLike`

error[E0407]: method `hash` is not a member of trait `salsa::HashEqLike`
   --> crates/ruff_python_ast/src/name.rs:219:5
    |
219 | /     fn hash<H: Hasher>(&self, state: &mut H) {
220 | |         Hash::hash(self, state);
221 | |     }
    | |_____^ not a member of trait `salsa::HashEqLike`

error[E0407]: method `hash` is not a member of trait `salsa::HashEqLike`
   --> crates/ruff_python_ast/src/name.rs:232:5
    |
232 | /     fn hash<H: Hasher>(&self, state: &mut H) {
233 | |         Hash::hash(self, state);
234 | |     }
    | |_____^ not a member of trait `salsa::HashEqLike`

For more information about this error, try `rustc --explain E0407`.
error: could not compile `ruff_python_ast` (lib) due to 3 previous errors
```

This surprised me, because salsa 0.28.2→0.28.4 was just a patch-release update.

### Version

ruff 0.16.8+844 (5bb508f59 2026-09-19)

**Comment by MichaReiser** [comment]
Hmm, it looks like our (Salsa's) release workflow didn't pick up on the signature change and failed to bump the minor. I don't have permissions to yank a release and we have a 7days dependency cooldown policy. Rust also doesn't have support for `cfg` based on dependency version.

For now, I'm leaning towards bumping Salsa on Friday. Can you say more when you run into this compile error? I would expect that building ruff from a fresh clone should succeed, unless you delete the lock file (or update salsa).

**Comment by musicinmybrain** [comment]
> Can you say more when you run into this compile error? I would expect that building ruff from a fresh clone should succeed, unless you delete the lock file (or update salsa).

Correct, this happens only downstream in Fedora where we build with system packaged versions of Rust libraries and don’t/can’t use the upstream `Cargo.lock` file. I updated our `rust-salsa*` packages from 0.28.2 to 0.28.4 without test-building `ruff` and `ty` since I didn’t expect any trouble from a patch release, and then I discovered this issue while doing unrelated work on our `ty` package.

This isn’t really an emergency on our end: I can let `ruff` and `ty` fail to build from source in Fedora for now, but not indefinitely. Within the next few weeks I’ll want to backport a patch or ship new `ruff`/`ty` releases that are compatible with a current `salsa` (👍). Otherwise I will have to consider downgrading our `rust-salsa*` packages (👎 because it permanently introduces an `Epoch` to the RPMs, but I can if I must).

**Comment by MichaReiser** [comment]
Thanks. I'll merge a PR to bump Salsa on Friday, which should fix this. We could also consider pinning Salsa for now (use `==` as dependency), if that would be helpful

**Comment by musicinmybrain** [comment]
> Thanks. I'll merge a PR to bump Salsa on Friday, which should fix this. We could also consider pinning Salsa for now (use `==` as dependency), if that would be helpful

Pinning it wouldn’t help downstream, since I would still have to downgrade our `rust-salsa*` packages from 0.28.4 back to 0.28.2 to satisfy the pin. Ideally, I could move forward, which would really only require knowing how to patch `ruff` to handle this change. So if `salsa` is bumped to 0.29, and then sometime in the next few weeks `ruff` is updated to support the new `salsa`, at least in `main`, then that’s great as far as I’m concerned.

**Comment by musicinmybrain** [comment]
And thank you for looking at this!

**Comment by musicinmybrain** [comment]
I was curious, so I checked if [cargo-semver-checks](https://crates.io/crates/cargo-semver-checks) was capable of flagging this change:

```
$ git status
HEAD detached at salsa-v0.28.4
nothing to commit, working tree clean
$ cargo semver-checks --quiet --baseline-version 0.28.2

--- failure trait_method_missing: pub trait method removed or renamed ---

Description:
A trait method is no longer callable, and may have been renamed or removed entirely.
        ref: https://doc.rust-lang.org/cargo/reference/semver.html#trait-item-signature
       impl: https://github.com/obi1kenobi/cargo-semver-checks/tree/v0.50.0/src/lints/trait_method_missing.ron

Failed in:
  method hash of trait HashEqLike, previously in file /home/ben/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/salsa-0.28.2/src/interned.rs:1424

```

**Comment by MichaReiser** [comment]
We updated directly to 0.28.5
