### ISSUE TITLE
B006 --fix --unsafe-fixes does not fix type to become Optional ( | None) (fails type check)

### ISSUE THREAD

**Issue by ehiggs** [astral-sh/ruff#9998]
Given the following file:

```python
def squares(x: list[int] = []) -> list[int]:
  return [i*i for i in x]
```
```
❯ ruff lint --select B006 ./b006.py
warning: Failed to lint lint: No such file or directory (os error 2)
b006.py:1:28: B006 Do not use mutable data structures for argument defaults
Found 1 error.
No fixes available (1 hidden fix can be enabled with the `--unsafe-fixes` option).
```

Let's fix it:

```
❯ ruff lint --select B006 --fix --unsafe-fixes ./b006.py
warning: Failed to lint lint: No such file or directory (os error 2)
Found 1 error (1 fixed, 0 remaining).
```

```python
def squares(x: list[int] = None) -> list[int]:
  if x is None:
    x = []
  return [i*i for i in x]
```

This code does not pass type check:

```
❯ mypy b006.py
b006.py:1: error: Incompatible default for argument "x" (default has type "None", argument has type "list[int]")  [assignment]
b006.py:1: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
b006.py:1: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
Found 1 error in 1 file (checked 1 source file)
```

**Comment by charliermarsh** [comment]
We actually have a separate rule that can catch and fix this: [`implicit-optional`](https://docs.astral.sh/ruff/rules/implicit-optional/). But it would be nice if `B006` worked independently.

**Comment by dhruvmanila** [comment]
Yeah, using `--select=B006,RUF013` should fix this although I agree that our fix infrastructure should be modular enough to be reused by other rules when relevant.

**Comment by spaceone** [comment]
same here:
```
+++ Lib/ldap/controls/sss.py
@@ -53,8 +53,10 @@ class SSSRequestControl(RequestControl):
     def __init__(
         self,
         criticality: bool = False,
-        ordering_rules: list[str] | str = [],
+        ordering_rules: list[str] | str = None,
     ):
+        if ordering_rules is None:
+            ordering_rules = []
         RequestControl.__init__(self,self.controlType,criticality)
         self.ordering_rules = ordering_rules
         if isinstance(ordering_rules, str):
```

needs `RUF013  implicit-optional` which then needs `UP045` `non-pep604-annotation-optional` and `I001 unsorted-imports` and `F401 unused-import`.
