### PR TITLE
remove unnecessary `__future__` import in `ruff.__main__`

### PR DESCRIPTION
**Pull request by jorenham**
## Summary

The `__future__.annotations` import in `ruff.__main__` was not needed, as there are no forward references or type-check-only imports.

Instead, I manually stringified the `list[str]` annotation, for compatibility with older Python versions.

Since the `pyproject.toml` ruff config for `isort` requires `__future__.annotations` to be present everywhere, I assumed that there must be some reason for that, and did not change it. I instead used a local `.ruff.toml` to override it for the only the `ruff` python package.

## Test Plan

Check that `python -m ruff` does not raise.

### CODE REVIEW

**Comment by MichaReiser** [comment]
Thank you.

The future annotation was introduced in https://github.com/astral-sh/ruff/pull/15090 to fix a runtime error. Nothing has changed to this file since then, so I think it's still needed

**Comment by jorenham** [comment]
> Thank you.
> 
> The future annotation was introduced in #15090 to fix a runtime error. Nothing has changed to this file since then, so I think it's still needed

I can't see how a `from __future__ import annotations` would fix the `FileNotFoundError` reported in #15090 🤔

**Comment by jorenham** [comment]
But either way, this indeed won't work now on older Python versions. Let me fix that real quick.

**Comment by MichaReiser** [comment]
I prefer keeping the future annotations because it protects against accidentially introducing backwards incompatible types and I don't see any harm to it.

**Comment by jorenham** [comment]
> I don't see any harm to it.

Usually it's no problem. But it can make the life of runtime type-checkers more difficult, because it requires them to `eval` all annotations because of that. But in this case I doubt that it matters, so I can see how the additional complexity might not be worth it here.
