### ISSUE TITLE
Build error for release profile on `x86_64-pc-windows-gnu`

### ISSUE THREAD

**Issue by T-256** [astral-sh/ruff#11586]
Debug profile, built successfully, but release profile produces errors. here is log file:
[err.log](https://github.com/astral-sh/ruff/files/15476110/err.log)

abstract:
```log
PS E:\crates\ruff> cargo b --release
   Compiling ruff_workspace v0.0.0 (E:\crates\ruff\crates\ruff_workspace)
   Compiling ruff_python_formatter v0.0.0 (E:\crates\ruff\crates\ruff_python_formatter)
   Compiling ruff_server v0.2.2 (E:\crates\ruff\crates\ruff_server)
error: linking with `x86_64-w64-mingw32-gcc` failed: exit code: 1
  |
  = note: "x86_64-w64-mingw32-gcc" "-fno-use-linker-plugin" "-Wl,--dynamicbase" "-Wl,  ...[75 KB more]
  = note: C:/msys2/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\crates\ruff\target\release\deps\ruff_python_formatter-a6d455985f2903e7.aho_corasick-4fc2a255abd66f6d.aho_corasick.61358d8f59a0b45d-cgu.07.rcgu.o.rcgu.o:aho_corasick.61358:(.text+0x20c3): undefined reference to `__imp__ZN6memchr4arch6x86_646memchr10memchr_raw2FN17h618d063ddc5353c7E'
          C:/msys2/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\crates\ruff\target\release\deps\ruff_python_formatter-a6d455985f2903e7.aho_corasick-4fc2a255abd66f6d.aho_corasick.61358d8f59a0b45d-cgu.07.rcgu.o.rcgu.o:aho_corasick.61358:(.text+0x2193): undefined reference to `__imp__ZN6memchr4arch6x86_646memchr11memchr2_raw2FN17hda836e9b9f82e15cE'
          C:/msys2/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\crates\ruff\target\release\deps\ruff_python_formatter-a6d455985f2903e7.aho_corasick-4fc2a255abd66f6d.aho_corasick.61358d8f59a0b45d-cgu.07.rcgu.o.rcgu.o:aho_corasick.61358:(.text+0x228d): undefined reference to `__imp__ZN6memchr4arch6x86_646memchr11memchr3_raw2FN17h7a7ed12eca0fefc9E'
          C:/msys2/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\crates\ruff\target\release\deps\ruff_python_formatter-a6d455985f2903e7.aho_corasick-4fc2a255abd66f6d.aho_corasick.61358d8f59a0b45d-cgu.07.rcgu.o.rcgu.o:aho_corasick.61358:(.text+0x234e): undefined reference to `__imp__ZN6memchr4arch6x86_646memchr10memchr_raw2FN17h618d063ddc5353c7E'
          C:/msys2/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\crates\ruff\target\release\deps\ruff_python_formatter-a6d455985f2903e7.aho_corasick-4fc2a255abd66f6d.aho_corasick.61358d8f59a0b45d-cgu.07.rcgu.o.rcgu.o:aho_corasick.61358:(.text+0x23e2): undefined reference to `__imp__ZN6memchr4arch6x86_646memchr11memchr2_raw2FN17hda836e9b9f82e15cE'
          C:/msys2/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\crates\ruff\target\release\deps\ruff_python_formatter-a6d455985f2903e7.aho_corasick-4fc2a255abd66f6d.aho_corasick.61358d8f59a0b45d-cgu.07.rcgu.o.rcgu.o:aho_corasick.61358:(.text+0x2477): undefined reference to `__imp__ZN6memchr4arch6x86_646memchr11memchr3_raw2FN17h7a7ed12eca0fefc9E'
          C:/msys2/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\crates\ruff\target\release\deps\ruff_python_formatter-a6d455985f2903e7.regex_automata-8087316b5b78a293.regex_automata.e1978bb43e0f5db-cgu.02.rcgu.o.rcgu.o:regex_automata.e19:(.text+0x7399): undefined reference to `__imp__ZN6memchr4arch6x86_646memchr11memchr3_raw2FN17h7a7ed12eca0fefc9E'
          C:/msys2/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\crates\ruff\target\release\deps\ruff_python_formatter-a6d455985f2903e7.regex_automata-8087316b5b78a293.regex_automata.e1978bb43e0f5db-cgu.02.rcgu.o.rcgu.o:regex_automata.e19:(.text+0x74a2): undefined reference to `__imp__ZN6memchr4arch6x86_646memchr11memchr2_raw2FN17hda836e9b9f82e15cE'
          C:/msys2/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\crates\ruff\target\release\deps\ruff_python_formatter-a6d455985f2903e7.regex_automata-8087316b5b78a293.regex_automata.e1978bb43e0f5db-cgu.02.rcgu.o.rcgu.o:regex_automata.e19:(.text+0x7593): undefined reference to `__imp__ZN6memchr4arch6x86_646memchr10memchr_raw2FN17h618d063ddc5353c7E'
          C:/msys2/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\crates\ruff\target\release\deps\ruff_python_formatter-a6d455985f2903e7.regex_automata-8087316b5b78a293.regex_automata.e1978bb43e0f5db-cgu.02.rcgu.o.rcgu.o:regex_automata.e19:(.text+0x79df): undefined reference to `__imp__ZN6memchr4arch6x86_646memchr11memchr2_raw2FN17hda836e9b9f82e15cE'
          C:/msys2/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\crates\ruff\target\release\deps\ruff_python_formatter-a6d455985f2903e7.regex_automata-8087316b5b78a293.regex_automata.e1978bb43e0f5db-cgu.02.rcgu.o.rcgu.o:regex_automata.e19:(.text+0x7ad3): undefined reference to `__imp__ZN6memchr4arch6x86_646memchr10memchr_raw2FN17h618d063ddc5353c7E'
          C:/msys2/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\crates\ruff\target\release\deps\ruff_python_formatter-a6d455985f2903e7.regex_automata-8087316b5b78a293.regex_automata.e1978bb43e0f5db-cgu.02.rcgu.o.rcgu.o:regex_automata.e19:(.text+0x7bd9): undefined reference to `__imp__ZN6memchr4arch6x86_646memchr11memchr3_raw2FN17h7a7ed12eca0fefc9E'
          C:/msys2/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\crates\ruff\target\release\deps\ruff_python_formatter-a6d455985f2903e7.regex_automata-8087316b5b78a293.regex_automata.e1978bb43e0f5db-cgu.02.rcgu.o.rcgu.o:regex_automata.e19:(.text+0x7f42): undefined reference to `__imp__ZN6memchr4arch6x86_646memchr11memchr3_raw2FN17h7a7ed12eca0fefc9E'
          C:/msys2/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\crates\ruff\target\release\deps\ruff_python_formatter-a6d455985f2903e7.regex_automata-8087316b5b78a293.regex_automata.e1978bb43e0f5db-cgu.02.rcgu.o.rcgu.o:regex_automata.e19:(.text+0x801f): undefined reference to `__imp__ZN6memchr4arch6x86_646memchr11memchr2_raw2FN17hda836e9b9f82e15cE'
          C:/msys2/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\crates\ruff\target\release\deps\ruff_python_formatter-a6d455985f2903e7.regex_automata-8087316b5b78a293.regex_automata.e1978bb43e0f5db-cgu.02.rcgu.o.rcgu.o:regex_automata.e19:(.text+0x8478): undefined reference to `__imp__ZN6memchr4arch6x86_646memchr10memchr_raw2FN17h618d063ddc5353c7E'
          C:/msys2/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\crates\ruff\target\release\deps\ruff_python_formatter-a6d455985f2903e7.regex_automata-8087316b5b78a293.regex_automata.e1978bb43e0f5db-cgu.02.rcgu.o.rcgu.o:regex_automata.e19:(.text+0x889c): undefined reference to `__imp__ZN6memchr4arch6x86_646memchr11memchr3_raw2FN17h7a7ed12eca0fefc9E'
          C:/msys2/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\crates\ruff\target\release\deps\ruff_python_formatter-a6d455985f2903e7.regex_automata-8087316b5b78a293.regex_automata.e1978bb43e0f5db-cgu.02.rcgu.o.rcgu.o:regex_automata.e19:(.text+0x89ae): undefined reference to `__imp__ZN6memchr4arch6x86_646memchr10memchr_raw2FN17h618d063ddc5353c7E'
          C:/msys2/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\crates\ruff\target\release\deps\ruff_python_formatter-a6d455985f2903e7.regex_automata-8087316b5b78a293.regex_automata.e1978bb43e0f5db-cgu.02.rcgu.o.rcgu.o:regex_automata.e19:(.text+0x8ab2): undefined reference to `__imp__ZN6memchr4arch6x86_646memchr11memchr2_raw2FN17hda836e9b9f82e15cE'
          C:/msys2/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\crates\ruff\target\release\deps\ruff_python_formatter-a6d455985f2903e7.regex_automata-8087316b5b78a293.regex_automata.e1978bb43e0f5db-cgu.02.rcgu.o.rcgu.o:regex_automata.e19:(.text+0x90fd): undefined reference to `__imp__ZN6memchr4arch6x86_646memchr11memchr2_raw2FN17hda836e9b9f82e15cE'
          C:/msys2/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\crates\ruff\target\release\deps\ruff_python_formatter-a6d455985f2903e7.regex_automata-8087316b5b78a293.regex_automata.e1978bb43e0f5db-cgu.02.rcgu.o.rcgu.o:regex_automata.e19:(.text+0x9237): undefined reference to `__imp__ZN6memchr4arch6x86_646memchr11memchr3_raw2FN17h7a7ed12eca0fefc9E'
          C:/msys2/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\crates\ruff\target\release\deps\ruff_python_formatter-a6d455985f2903e7.regex_automata-8087316b5b78a293.regex_automata.e1978bb43e0f5db-cgu.02.rcgu.o.rcgu.o:regex_automata.e19:(.text+0x9362): undefined reference to `__imp__ZN6memchr4arch6x86_646memchr10memchr_raw2FN17h618d063ddc5353c7E'
          C:/msys2/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\crates\ruff\target\release\deps\ruff_python_formatter-a6d455985f2903e7.regex_automata-8087316b5b78a293.regex_automata.e1978bb43e0f5db-cgu.05.rcgu.o.rcgu.o:regex_automata.e19:(.text+0x32de): undefined reference to `__imp__ZN6memchr4arch6x86_646memchr10memchr_raw2FN17h618d063ddc5353c7E'
          C:/msys2/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\crates\ruff\target\release\deps\ruff_python_formatter-a6d455985f2903e7.regex_automata-8087316b5b78a293.regex_automata.e1978bb43e0f5db-cgu.05.rcgu.o.rcgu.o:regex_automata.e19:(.text+0x33e2): undefined reference to `__imp__ZN6memchr4arch6x86_646memchr11memchr2_raw2FN17hda836e9b9f82e15cE'
          C:/msys2/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\crates\ruff\target\release\deps\ruff_python_formatter-a6d455985f2903e7.regex_automata-8087316b5b78a293.regex_automata.e1978bb43e0f5db-cgu.05.rcgu.o.rcgu.o:regex_automata.e19:(.text+0x3517): undefined reference to `__imp__ZN6memchr4arch6x86_646memchr11memchr3_raw2FN17h7a7ed12eca0fefc9E'
          C:/msys2/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\crates\ruff\target\release\deps\ruff_python_formatter-a6d455985f2903e7.ruff_python_formatter-d04e736c2481ef8a.ruff_python_formatter.9dee42ec154ec7d4-cgu.08.rcgu.o.rcgu.o:ruff_python_format:(.text+0x3966): undefined reference to `__imp__ZN6memchr4arch6x86_646memchr11memchr2_raw2FN17hda836e9b9f82e15cE'
          C:/msys2/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\crates\ruff\target\release\deps\ruff_python_formatter-a6d455985f2903e7.ruff_python_formatter-d04e736c2481ef8a.ruff_python_formatter.9dee42ec154ec7d4-cgu.12.rcgu.o.rcgu.o:ruff_python_format:(.text+0x4d37): undefined reference to `__imp__ZN6memchr4arch6x86_646memchr11memchr2_raw2FN17hda836e9b9f82e15cE'
          C:/msys2/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\crates\ruff\target\release\deps\ruff_python_formatter-a6d455985f2903e7.ruff_python_formatter-d04e736c2481ef8a.ruff_python_formatter.9dee42ec154ec7d4-cgu.14.rcgu.o.rcgu.o:ruff_python_format:(.text+0x343f): undefined reference to `__imp__ZN6memchr4arch6x86_646memchr10memchr_raw2FN17h618d063ddc5353c7E'
          C:/msys2/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\crates\ruff\target\release\deps\ruff_python_formatter-a6d455985f2903e7.ruff_python_parser-fda4f126870e947c.ruff_python_parser.b89a1574932f071c-cgu.0.rcgu.o.rcgu.o:ruff_python_parser:(.text+0xfb72): undefined reference to `__imp__ZN6memchr4arch6x86_646memchr11memchr2_raw2FN17hda836e9b9f82e15cE'
          C:/msys2/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\crates\ruff\target\release\deps\ruff_python_formatter-a6d455985f2903e7.ruff_python_parser-fda4f126870e947c.ruff_python_parser.b89a1574932f071c-cgu.0.rcgu.o.rcgu.o:ruff_python_parser:(.text+0x1086a): undefined reference to `__imp__ZN6memchr4arch6x86_646memchr11memchr3_raw2FN17h7a7ed12eca0fefc9E'
          C:/msys2/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\crates\ruff\target\release\deps\ruff_python_formatter-a6d455985f2903e7.ruff_python_parser-fda4f126870e947c.ruff_python_parser.b89a1574932f071c-cgu.0.rcgu.o.rcgu.o:ruff_python_parser:(.text+0x108a3): undefined reference to `__imp__ZN6memchr4arch6x86_646memchr10memchr_raw2FN17h618d063ddc5353c7E'
          C:/msys2/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\crates\ruff\target\release\deps\ruff_python_formatter-a6d455985f2903e7.ruff_python_parser-fda4f126870e947c.ruff_python_parser.b89a1574932f071c-cgu.0.rcgu.o.rcgu.o:ruff_python_parser:(.text+0x1d2c3): undefined reference to `__imp__ZN6memchr4arch6x86_646memchr10memchr_raw2FN17h618d063ddc5353c7E'
          C:/msys2/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\crates\ruff\target\release\deps\ruff_python_formatter-a6d455985f2903e7.ruff_python_parser-fda4f126870e947c.ruff_python_parser.b89a1574932f071c-cgu.0.rcgu.o.rcgu.o:ruff_python_parser:(.text+0x1d3dc): undefined reference to `__imp__ZN6memchr4arch6x86_646memchr10memchr_raw2FN17h618d063ddc5353c7E'
          C:/msys2/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\crates\ruff\target\release\deps\ruff_python_formatter-a6d455985f2903e7.ruff_python_parser-fda4f126870e947c.ruff_python_parser.b89a1574932f071c-cgu.0.rcgu.o.rcgu.o:ruff_python_parser:(.text+0x1dd81): undefined reference to `__imp__ZN6memchr4arch6x86_646memchr10memchr_raw2FN17h618d063ddc5353c7E'
          C:/msys2/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\crates\ruff\target\release\deps\ruff_python_formatter-a6d455985f2903e7.ruff_python_parser-fda4f126870e947c.ruff_python_parser.b89a1574932f071c-cgu.0.rcgu.o.rcgu.o:ruff_python_parser:(.text+0x1fabc): undefined reference to `__imp__ZN6memchr4arch6x86_646memchr11memchr3_raw2FN17h7a7ed12eca0fefc9E'
          C:/msys2/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\crates\ruff\target\release\deps\ruff_python_formatter-a6d455985f2903e7.ruff_python_parser-fda4f126870e947c.ruff_python_parser.b89a1574932f071c-cgu.0.rcgu.o.rcgu.o:ruff_python_parser:(.text+0x20b01): undefined reference to `__imp__ZN6memchr4arch6x86_646memchr11memchr3_raw2FN17h7a7ed12eca0fefc9E'
          C:/msys2/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\crates\ruff\target\release\deps\ruff_python_formatter-a6d455985f2903e7.ruff_source_file-9e3527bffbe461b0.ruff_source_file.d34ff7af2c172c7c-cgu.01.rcgu.o.rcgu.o:ruff_source_file.d:(.text+0x132): undefined reference to `__imp__ZN6memchr4arch6x86_646memchr12memrchr2_raw2FN17h77df0598d0fcb37bE'
          C:/msys2/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\crates\ruff\target\release\deps\ruff_python_formatter-a6d455985f2903e7.ruff_source_file-9e3527bffbe461b0.ruff_source_file.d34ff7af2c172c7c-cgu.01.rcgu.o.rcgu.o:ruff_source_file.d:(.text+0x242): undefined reference to `__imp__ZN6memchr4arch6x86_646memchr11memchr2_raw2FN17hda836e9b9f82e15cE'
          C:/msys2/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\crates\ruff\target\release\deps\ruff_python_formatter-a6d455985f2903e7.tracing-a3877614066def19.tracing.5441c59aa9d48259-cgu.01.rcgu.o.rcgu.o:tracing.5441c59aa9:(.text+0x85): undefined reference to `__imp__ZN12tracing_core10dispatcher15GLOBAL_DISPATCH17h1c5a9e6d56948a0dE'
          C:/msys2/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\crates\ruff\target\release\deps\ruff_python_formatter-a6d455985f2903e7.tracing-a3877614066def19.tracing.5441c59aa9d48259-cgu.01.rcgu.o.rcgu.o:tracing.5441c59aa9:(.text+0xa1): undefined reference to `__imp__ZN12tracing_core10dispatcher15GLOBAL_DISPATCH17h1c5a9e6d56948a0dE'
          C:/msys2/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\crates\ruff\target\release\deps\ruff_python_formatter-a6d455985f2903e7.tracing-a3877614066def19.tracing.5441c59aa9d48259-cgu.01.rcgu.o.rcgu.o:tracing.5441c59aa9:(.text+0x279): undefined reference to `__imp__ZN12tracing_core10dispatcher15GLOBAL_DISPATCH17h1c5a9e6d56948a0dE'
          C:/msys2/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\crates\ruff\target\release\deps\ruff_python_formatter-a6d455985f2903e7.tracing-a3877614066def19.tracing.5441c59aa9d48259-cgu.01.rcgu.o.rcgu.o:tracing.5441c59aa9:(.text+0x2a7): undefined reference to `__imp__ZN12tracing_core10dispatcher15GLOBAL_DISPATCH17h1c5a9e6d56948a0dE'
          collect2.exe: error: ld returned 1 exit status

  = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#rustc-link-lib)

error: could not compile `ruff_python_formatter` (bin "ruff_python_formatter") due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

**Comment by MichaReiser** [comment]
Okay, I'm able to build ruff after I disabled link time optimizations (setting `lto=false` in `Cargo.toml`). The build even succeeds when I set `lto="fat"`. 

I'm still unable to reproduce this with ripgrep. Setting `lto` to `flat` doesn't trigger the issue. 

This makes me wonder if, by chance, this is a linker issue. @BurntSushi any guesses?

**Comment by T-256** [comment]
Reproduced same on GHA:
https://github.com/T-256/ruff/actions/runs/9284396370/job/25546692607

**Comment by T-256** [comment]
Regressed by https://github.com/astral-sh/ruff/pull/9031 and related to https://github.com/astral-sh/ruff/issues/9245.

Workaround:
> Since [per-target profiles](https://github.com/rust-lang/cargo/issues/4897) aren't really a thing, I was able to get around this issue by setting the environment variable `CARGO_PROFILE_RELEASE_LTO` to `false`. This'll work for me for now until https://github.com/rust-lang/rust/issues/109797 is fixed.

_Originally posted by @cr1901 in https://github.com/astral-sh/ruff/issues/9245#issuecomment-1950273225_

**Comment by MichaReiser** [comment]
@T-256 nice for finding these details. I guess a work around on our side could be to set LTO to "fat" for this specific target (I think that's possible?)

**Comment by BurntSushi** [comment]
Yeah the specific bug is related to something about inlining functions with statics: https://github.com/rust-lang/rust/issues/109797

And see also: https://github.com/BurntSushi/memchr/issues/145

**Comment by mati865** [comment]
Another workaround is to link with LLD instead of default ld.bfd, that way you can still use ThinLTO.

**Comment by T-256** [comment]
@mati865 I tested with 
```toml
[target.x86_64-pc-windows-gnu]
linker = "rust-lld"
```
but I got errors even on `lto=off`

**Comment by mati865** [comment]
@T-256 you cannot use LLD like that for Unix and windows-gnu targets, it has to be called through the compiler to add the libraries.
With stable Rust you can use LLD from your PATH with `-Clink-arg=-fuse-ld=lld` or `rust-lld` provided by Rust using nightly `-Zlinker-features=+lld`.
