### PR TITLE
Update to Rust 1.74 and use new clippy lints table

### PR DESCRIPTION
**Pull request by konstin**
Update to [Rust 1.74](https://blog.rust-lang.org/2023/11/16/Rust-1.74.0.html) and use the new clippy lints table.

The update itself introduced a new clippy lint about superfluous hashes in raw strings, which got removed.

I moved our lint config from `rustflags` to the newly stabilized [workspace.lints](https://doc.rust-lang.org/stable/cargo/reference/workspaces.html#the-lints-table). One consequence is that we have to `unsafe_code = "warn"` instead of "forbid" because the latter now actually bans unsafe code:

```
error[E0453]: allow(unsafe_code) incompatible with previous forbid
  --> crates/ruff_source_file/src/newlines.rs:62:17
   |
62 |         #[allow(unsafe_code)]
   |                 ^^^^^^^^^^^ overruled by previous forbid
   |
   = note: `forbid` lint level was set on command line
```

### CODE REVIEW

**Review by BurntSushi — APPROVED** [review]
Nice!

**Review by charliermarsh — APPROVED** [review]
Dumb question: will Ruff still compile on Rust 1.71, given that that's what we have in our `Cargo.toml` as the `rust-version`? (I'm just wondering if this will cause issues if Conda or Homebrew aren't updated yet.)
